account/urls.py
# account/urls.py

from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "account"

urlpatterns = [
    path("create", views.create, name="create"), # http://ip:port/account/create
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("detail", TemplateView.as_view(template_name="account/detail.html"), name="detail"),
    path("password_change", views.password_change, name="password_change"),
    path("update", views.user_update, name="update"),
    path('delete', views.user_delete, name="delete"),

]

config/urls.py
# config/urls.py 
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from polls import views

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    # path('polls/welcome', views.welcome_poll, name="welcome"),
    path("polls/", include('polls.urls')),
    path("account/", include("account.urls")),
]
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 파일 업로드관련 설정. "MEDIA_URL" 로 요청이 들어오면 
#     어느 경로(MEDIA_ROOT)의 파일들을 제공할 것인지 설정.
# Django 개발서버에서 필요한 설정.
# 운영시 웹서버(HTTP서버) 와 django 실행 환경(wsgi)을 분리해서 운영환경을 정의 할 경우
# 웹 서버에게 MEDIA_ROOT 경로를 설정하는 것으도 대신한다.


# path('polls/welcome', views.welcome_poll, name="welcome"),
# 사용자가 http://127.0.0.1:8000/polls/welcome 요청하면
# views.welcome_poll 함수를 호출해서 실행.

# path("polls/", include('polls.urls')),
# 사용자가 http://127.0.0.1:8000/polls/ 로 시작하는 url로 요청하면
# polls 앱의 urls.py 모듈에 가서 url-mapping을 확인해라.

polls/urls.py
# polls/urls.py - polls app의 url-mapping을 설정
## url - view

from django.urls import path
from . import views

app_name = "polls"
# url mapping 설정으로 호출할 때 사용할 접두어 설정.
## welcome 호출 -> polls:welcome

urlpatterns = [
    path("welcome", views.welcome_poll, name="welcome"),
    path("vote_list", views.list, name="list"),
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path("vote_create", views.vote_create, name="vote_create"),
    path("", views.list, name="polls_main"), # http://127.0.0.1:8000/polls/
]
# python manage.py runserver
# http://127.0.0.1:8000/polls/list -> views.list() -> list.html -> User
# http://127.0.0.1:8000/polls/vote_form/질문ID -> path parameter 설정
# http://127.0.0.1:8000/polls/vote -> 투표처리

# http://127.0.0.1:8000/polls/vote_result/1

# http://127.0.0.1:8000/polls/vote_create

### <타입:받을view의파라미터이름>

templates/layouts/main_layout.html
<!-- mypoll/templates/layouts/main_layout.html -->
<!-- 모든 페이지의 공통부분을 구현한 template  -->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
    <title>{%block title%}설문{%endblock title%}</title>
</head>
<body>
<!-- 
    메뉴 - nav 
    로그인 여부와 관계없이 나오는 메뉴: 설문 목록
    로그인 안한 상태에서 나오는 메뉴: 가입, 로그인
    로그인 한 상태에서 나오는 메뉴:  설문등록, 로그아웃, 사용자이름(정보조회)  
                                    설문 참여(투표)      
-->
{#{user.username}} {{user.name}} {{user.email}} {{user.birthday}#}
{# {{user}}, {{user.is_authenticated}} #}
<nav class="navbar navbar-expand-sm bg-success bg-opacity-10">
    <div class="container">
        <div class="navbar-nav">
            <a href="{% url 'polls:list' %}" class="nav-link">설문목록</a>
            {% if user.is_authenticated %}
                <a href="{% url 'polls:vote_create' %}" class="nav-link">설문등록</a>
                <a href="{% url 'account:logout' %}" class="nav-link">로그아웃</a>
                <a href="{% url 'account:detail' %}"class="nav-link">{{user.name}}</a>
            {% endif %}
            {% if not user.is_authenticated %}
                <a href="{% url 'account:create' %}" class="nav-link">가입</a>
                <a href="{% url 'account:login' %}" class="nav-link">로그인</a>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container mt-3">
{%block contents%}{%endblock contents%}
</div>
</body>
</html>