config/urls.py
# config/urls.py 
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from polls import views

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    # path('polls/welcome', views.welcome_poll, name="welcome"),
    path("polls/", include('polls.urls')),
    path("account/", include("account.urls")),
]
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 파일 업로드관련 설정. "MEDIA_URL" 로 요청이 들어오면 
#     어느 경로(MEDIA_ROOT)의 파일들을 제공할 것인지 설정.
# Django 개발서버에서 필요한 설정.
# 운영시 웹서버(HTTP서버) 와 django 실행 환경(wsgi)을 분리해서 운영환경을 정의 할 경우
# 웹 서버에게 MEDIA_ROOT 경로를 설정하는 것으도 대신한다.


# path('polls/welcome', views.welcome_poll, name="welcome"),
# 사용자가 http://127.0.0.1:8000/polls/welcome 요청하면
# views.welcome_poll 함수를 호출해서 실행.

# path("polls/", include('polls.urls')),
# 사용자가 http://127.0.0.1:8000/polls/ 로 시작하는 url로 요청하면
# polls 앱의 urls.py 모듈에 가서 url-mapping을 확인해라.

polls/urls.py
# polls/urls.py - polls app의 url-mapping을 설정
## url - view

from django.urls import path
from . import views

app_name = "polls"
# url mapping 설정으로 호출할 때 사용할 접두어 설정.
## welcome 호출 -> polls:welcome

urlpatterns = [
    path("welcome", views.welcome_poll, name="welcome"),
    path("vote_list", views.list, name="list"),
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path("vote_create", views.vote_create, name="vote_create"),
    path("", views.list, name="polls_main"), # http://127.0.0.1:8000/polls/
]
# python manage.py runserver
# http://127.0.0.1:8000/polls/list -> views.list() -> list.html -> User
# http://127.0.0.1:8000/polls/vote_form/질문ID -> path parameter 설정
# http://127.0.0.1:8000/polls/vote -> 투표처리

# http://127.0.0.1:8000/polls/vote_result/1

# http://127.0.0.1:8000/polls/vote_create

### <타입:받을view의파라미터이름>

polls/models.py
# polls/models.py

from django.db import models

# Model class ---- DB Table
## DB 테이블당 Model class를 정의
## django.db.models.Model 를 상속
## class변수로 DB Table의 컬럼과 연결된 변수들(Field)를 선언.
### - 변수명(컬럼명) = ModelField(type, 제약조건등 설정)

# Question (설문의 질문을 저장할 Model(table))
class Question(models.Model):
    # Model Field 들 선언 
    ## primay_key 컬럼을 선언하지 않으면 "`id`: 정수 자동증가 컬럼" 이 
    #                                              primary key 컬럼으로 생성된다.

    # question_text(질문) - varchar(문자열 - max length: 200)
    question_text = models.CharField(max_length=200)  # CharField == varchar
    # pub_date (질문 등록 일시) - datetime
    pub_date = models.DateTimeField(auto_now_add=True) # DateTimeField == datetime
    # auto_now_add - 처음 insert할 때 시점의 일시를 자동으로 저장(등록일시)
    # auto_now - insert/update 할 때 시점의 일시를 자동으로 저장(수정일시)

    # default: not null. Field에서 nullable 설정-> null=True
   
    def __str__(self):
        # 모델 instance를 출력/문자열로변환 할때 나올 값을 str로 반환.
        # self.Field 명 -> Field(테이블 컬럼)의 값
        # self.pk -> Primary key Field의 값을 반환.
        return f"{self.pk}. {self.question_text}"


# Choice(질문의 보기들을 저장할 Model)
class Choice(models.Model):
    
    choice_text = models.CharField(max_length=200) # 보기 문장
    votes = models.IntegerField(default=0) # insert할 때 값을 넣지 않으면 저장할 기본값을 설정(default)
    question = models.ForeignKey(
        Question, # 참조 모델 클래스
        on_delete=models.CASCADE, # 부모 테이블에서 참조하는 값이 삭제되면 같이 삭제. (models.SET_NULL - NULL로 업데이트)
    )
    # FK 설정 - ForeignKey(참조 Model클래스, on_delete설정)
    # class Meta:
    #     db_table="테이블이름"
    def __str__(self):
        return f"{self.pk}. {self.choice_text}"

# python manage.py makemigrations   [polls]
# python manage.py migrate

polls/views.py
# polls/views.py - view들을 구현
# view: 하나의 사용자 요청을 처리하는 함수
# View 함수 정의
## 1. view 함수, 
## 2. urls.py에 설정(url-view함수 매핑), 
## 3. template(응답화면이 있는 경우)

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse # urls.py의 path이름으로 설정된 url을 조회하는 메소드
from django.core.paginator import Paginator

from django.contrib.auth.decorators import login_required

from datetime import datetime 
from .models import Question, Choice # 모델 클래스들 import

def welcome_poll_old(request):
    # view 함수 -> 1개 이상의 파라미터를 선언. (1개 필수-HttpRequest객체를 받는다.)
    now = datetime.now().strftime("%Y년 %m월 %d일 %H시 %M분 %S초") #실행시점의 일시
    res_html = f"""<!doctype html>
<html>
    <head>
        <title>Welcome Poll</title>
    </head>
    <body>
        <h1>설문조사 APP</h1>
        현재시간: {now}
    </body>
</html>
"""
    return HttpResponse(res_html)

def welcome_poll(request):
    now = datetime.now().strftime("%Y년 %m월 %d일 %H시 %M분 %S초")
    # template 을 이용해서 응답 페이지를 생성.
    response = render(
        request,              # HttpRequest
        "polls/welcome.html", # template파일의 경로(app_directory/templates 이후 경로)
        {"now": now, "name":"홍길동"} 
        # view가 template에 전달할 값들을 dictionary에 name-value 로 묶어서 전달.
        #    -> context value라고 한다.
    )
    # response: HttpResponse(polls/welcome.html 처리 내용)
    print("=============", type(response))
    return response
# http://127.0.0.1:8000/polls/welcome


##########################################
# 설문 질문 목록을 출력하는 View
#
# url: polls/list
# view함수: list
# template: polls(app)/templates/polls/list.html

def list_no_paging(request):
    # DB에서 question들을 조회
    q_list = Question.objects.all().order_by("-pub_date")

    # render(): template을 실행 해서 그 결과로 HttpResponse를 반환하는 함수.
    return render(
        request,  # HttpRequest객체
        "polls/list.html", # Template 파일의 경로
        {"question_list" : q_list} 
        # template에게 전달할 값 -> context value: dictionary
    )

####################################
# list -> paging 처리 목록 View
# - 요청파라미터(querystring)으로 page 번호를 받는다.
# - 응답 context value(data) 
#   - 현재 page에 보여줄 데이터들
#   - 현재 페이지가 속한 페이지 그룹의 시작/끝 페이지 번호
#   - 현재 페이지 그룹의 시작페이지가 **이전페이지가 있는지 여부/이전 페이지번호**
#   - 현재 페이지 그룹의 끝 페이지가 **다음페이지가 있는지 여부/다음 페이지번호**
def list(request):
    paginate_by = 10      # 한 페이지당 데이터 개수.
    page_group_count = 10 # 한 페이지그룹당 페이지 개수
    # http://ip:port/polls/list?page=15
    current_page = int(request.GET.get('page', 1)) # 현재 조회하려는 페이지번호

    # Question 데이터 조회 + Paginator객체 생성
    question_list = Question.objects.all().order_by("-pk")
    pn = Paginator(question_list, paginate_by)

    # 현재 페이지가 속한 페이지그룹의 start/end 페이지 번호 조회
    start_index = int((current_page - 1) / page_group_count) * page_group_count
    end_index = start_index + page_group_count
    page_range = pn.page_range[start_index : end_index]

    # context_value(context_data) -> template에 전달할 값들. dictionary
    context_value = {
        "page_range": page_range,  # Page group의 시작/끝페이지 range
        "question_list": pn.page(current_page),  # 페이지의 데이터들.
    }

    # 페이지그룹의 시작 페이지가 이전 페이지가 있는지, 이전페이지 번호는 무언지
    start_page = pn.page(page_range[0])
    has_previous = start_page.has_previous()
    if has_previous:
        previous_page = start_page.previous_page_number()
        context_value['has_previous'] = has_previous
        context_value['previous_page'] = previous_page
    # 페이지그룹의 끝 페이지가 다음 페이지가 있는지, 다음 페이지 번호는 무언지
    end_page = pn.page(page_range[-1])
    has_next = end_page.has_next()
    if has_next:
        next_page = end_page.next_page_number()
        context_value['has_next'] = has_next
        context_value['next_page'] = next_page

    return render(request, "polls/list.html", context_value)



################################
# 개별 설문 페이지로 이동하는 View
#  - 설문 질문 id를 받아서 그 질문에 대해 보기를 선택할 수있는 페이지를 응답
#
# url: polls/vote_form/질문_id   ex) polls/vote_form/3
# view 함수: vote_form
# template: polls/vote_form.html

def vote_form(request, question_id):
    # question_id: path parameter로 넘어온 값을 받을 변수
    question = Question.objects.get(pk=question_id)

    # 응답 -> html
    return render(request, "polls/vote_form.html", {"question":question})

###################################
# 투표 처리
#  - choice_id 받아서 votes 을 1 증가 
#  - 응답: 정상처리 - 투표 결과를 응답. 질문 - 보기(choice_text, votes)
#          요청파라미터 검증 실패(아무것도 선택안하고 요청) - vote_form.html 이동(다시투표하도록)
#
# url: polls/vote
# view함수: vote
# 응답 : 정상 - vote_result.html, 
#        오류 - vote_form.html

# View 함수에서 요청파라미터 값들 조회
## GET:  request.GET - 요청파라미터가 dictionary에 담겨서 제공.
## POST: request.POST- 요청파라미터가 dictionary에 담겨서 제공.
@login_required
def vote(request):
    # 1. 요청파라미터 조회
    # question_id = request.POST['question_id']  # 없으면 Exception
    question_id = request.POST.get('question_id')# 없으면 None
    choice_id = request.POST.get('choice')

    ##############################
    # 쿠키(Cookie)를 이용해서 이미 투표한 적이 있는 질문이면 투표를 못하게 처리.
    #   - 쿠키 연습용(실제는 DB를 통해 처리해야 한다.)
    # 1. 쿠키 voted_question 에 question_id가 있는지 여부를 확인
    #   - 있으면 error_message와 함께 vote_form으로 이동
    # 2. 투표 처리 후 쿠키 voted_question에 투표한 question_id를 추가.
    
    voted_question_ids = request.COOKIES.get("voted_question") # 쿠키값을 조회
    if voted_question_ids is not None:
        # 투표한 질문ID를 쿠키에 "1,2,3,10,5" `,` 를 구분자로 저장.
        question_ids = voted_question_ids.split(',') # "1,2,3,10,5" => ['1', '2', '3', '10', '5']
        if question_id in question_ids: # 이미 투표한 질문
            question = Question.objects.get(pk=question_id)
            return render(request, "polls/vote_form.html", 
                          {"question":question, "error_message":"이미 투표한 설문입니다."})

    # 2. 요청파라미터 검증 -> choice가 선택되었는지 여부
    if choice_id: # 선택이 된 경우(정상처리)
        # votes를 1 증가
        choice = Choice.objects.get(pk=choice_id)
        choice.votes += 1
        choice.save()
        # # 응답페이지이동 -> Question객체
        # question = Question.objects.get(pk=question_id)
        # return render(request, "polls/vote_result.html", {"question":question})

        # vote_result를 요청하도록 응답. - http응답 상태코드: 302, 이동할 url  ==> redirect()
        # response = redirect(f"/polls/vote_result/{question_id}")
        url = reverse("polls:vote_result", args=[question_id])  # app_name이 polls인 urls.py에서 name=vote_result인 설정의 url을 조회
        print("reverse()가 생성한 url:", type(url), url)
        response = redirect(url)
        print(type(response))
        
        # voted_question 쿠키에 투표한 질문 ID를 셋팅
        ## 처음 투표일 경우 (voted_questioN_ids == None) 는 "question_id" 반환
        ## 기존 투표한 값이 있을 경우 "1,2,3,question_id" 형태로 기존것에 추가해서 반환.
        voted_question_ids = str(question_id) \
                             if voted_question_ids is None \
                             else f"{voted_question_ids},{question_id}"
        print(voted_question_ids)
        response.set_cookie("voted_question", voted_question_ids
                            ,max_age=60*60*24*365) # max_age=초 : cookie가 client에서 유지할 시간
                                                   # max_age=0 - 삭제

        return response
    
    else: # 선택 안된 경우(예외상황) -> vote_form.html 이동
        question = Question.objects.get(pk=question_id)
        return render(
            request, 
            "polls/vote_form.html", 
            {"question": question, "error_message":"보기를 선택하세요."}
        )
    
#################################
# question_id를 받아서 그 질문의 투표 결과를 응답하는 View
#
# URL: polls/vote_result/질문_id
# view: vote_result
# 응답 template: polls/vote_result.html
def vote_result(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, "polls/vote_result.html", {"question":question})

####################################################
# 설문 질문 등록
#  
#  요청 url: polls/vote_create
#  view 함수: vote_create
##   -  GET방식요청 : 등록 폼을 제공
##   -  POST방식요청: 등록 처리
#  응답 template
##    - GET방식요청 : polls/vote_create.html
##    - POST방식요청: list로 이동 => redirect 방식으로 이동.

# HTTP 요청방식 조회 - HttpRequest.method => "GET", "POST"
@login_required
def vote_create(request):
    http_method = request.method
    if http_method == "GET":
        return render(request, "polls/vote_create.html")
    elif http_method == "POST":
        # 요청파라미터 읽기 - 질문, 보기들
        question_text = request.POST.get("question_text")
        # 같은이름으로 여러개 값이 전달된 경우 getlist("요청파라미터이름"): list
        choice_list = request.POST.getlist("choice_text")

        #  DB에 저장
        q = Question(question_text=question_text)
        q.save()
        for choice_text in choice_list:
            c = Choice(choice_text=choice_text, question=q)
            c.save()

        #  응답 - list로 redirect방식으로 이동.
        # return redirect("/polls/list")
        return redirect(reverse("polls:list"))

polls/templates/polls/list.html
<!-- polls/templates/polls/list.html -->
{% extends "layouts/main_layout.html" %}

{% block title%}설문 목록{%endblock title%}

{% block contents%}
    <h1>설문 목록</h1>
    <div class="list-group">
        {% for question in question_list %}
            <!--a href="/polls/vote_form/{{question.pk}}" -->
            <a href="{% url 'polls:vote_form' question.pk %}" 
               class="list-group-item list-group-item-action">
                {{question.pk}}. {{question.question_text | truncatewords:4}}
            </a>
        {% empty %}
            <b>등록된 설문이 없습니다.</b>
        {% endfor %}
    </div>

    <!-- paging 처리 -> 이동할 페이지 링크 추가 -->
    <ul class="pagination mt-3">
        {# 이전 페이지그룹 이동 버튼#}
        {% if has_previous %}
            <li class="page-item">
                <a href="{% url 'polls:list' %}?page={{previous_page}}" class="page-link">
                    이전
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <span class="page-link disabled">이전</span>
            </li>
        {% endif %}

        {# 이동할 페이지 번호, 링크 - 현재페이지는 링크를 걸지 않는다. #}
        {% for page_no in page_range %}
            {% if page_no == question_list.number %}
                <li class="page-item">
                    <span class="page-link disabled">{{page_no}}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a href="{% url 'polls:list' %}?page={{page_no}}" class="page-link">
                        {{page_no}}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {# 다음 페이지그룹 이동 버튼#}
        {% if has_next %}
            <li class="page-item">
                <a href="{% url 'polls:list' %}?page={{next_page}}" class="page-link">
                    다음
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <span class="page-link disabled">다음</span>
            </li>
        {% endif %}
    </ul>
{% endblock contents%}

polls/templates/polls/vote_create.html
<!--polls/templates/polls/vote_create.html-->
{% extends "layouts/main_layout.html"%}
{% block title%}설문 등록{% endblock title%}
{% block contents%}
<h1>설문 질문 등록</h1>
<!-- ACTION 생략: 현재 url로 요청. form요청, 등록 처리가 같은 url이기 때문에 action을 생략 -->
<form method="post">
    {% csrf_token %}
    <h2>질문</h2>
    <input type="text" name="question_text" required class="form-control">
    <h2>보기</h2>
    <div id="choice_layer">
        <input type="text" name="choice_text" required class="form-control">
    </div>
    <div class="mt-3">
        <button type="button" onclick="addChoice();" class="btn btn-primary">보기추가</button>
        <button type="button" onclick="delChoice();" class="btn btn-primary">보기삭제</button>
        <button type="submit" class="btn btn-primary">문제등록</button>
    </div>
</form>
<script>
    function addChoice() {
        // 보기 입력 input form을 추가하는 함수.
        input = document.createElement("input");  // <input>
        input.setAttribute("type", "text");       // <input type="text">
        input.setAttribute("name", "choice_text");// <input type="text" name="choice_text">
        input.setAttribute("required", true); //<input type="text" name="choice_text" required>
        input.setAttribute("class", "form-control");
        div = document.getElementById("choice_layer");
        div.append(input);
    }
    function delChoice() {
        // 보기 입력 input form이 두개 이상일때 마지막 입력form을 제거하는 함수. 
        // 하나만 있을 경우는 삭제하지 않도록 처리.
        div = document.getElementById("choice_layer");
        if (div.children.length >= 2) {
            div.removeChild(div.lastChild);
        }else { // 한개만 있는 경우
            alert("보기가 하나일 경우 삭제할 수없습니다.");
        }
    }
</script>
{%endblock contents%}

polls/templates/polls/vote_form.html
<!-- polls/templates/polls/vote_form.html -->
{% extends "layouts/main_layout.html" %}

{% block title%}설문폼{%endblock title%}
{% block contents %}
<h1>설문</h1>
<h2>질문: {{question.pk}}. {{question.question_text}}</h2>
설문등록일시: {{question.pub_date | date:'Y/m/d H:i:s'}}
<br><br>
{% if error_message %}
    <div style="color:red;font-size:0.8em">
        {{error_message}}
    </div>
{% endif %}

<form action="{% url 'polls:vote' %}" method="post">
    {% csrf_token %}  <!--post 요청일 경우 필수로 csrf_token 태그를 사용.-->

    <input type="hidden" name="question_id" value="{{question.pk}}">
    {% for choice in question.choice_set.all %}
        <label for="{{choice.pk}}">{{choice.choice_text}}</label>
        <input type="radio" name="choice" value="{{choice.pk}}" id="{{choice.pk}}"><br>
    {% endfor %}
    
    {# 로그인 안한 경우 투표를 못하도록 처리 #}
    {% if user.is_authenticated %}
        <button type="submit" class="btn btn-primary">투표</button>
        <button type="reset" class="btn btn-primary">선택해제</button>
    {% endif %}
</form>
{% endblock contents %}

polls/templates/polls/vote_result.html
<!-- polls/templates/polls/vote_result.html -->
{% extends "layouts/main_layout.html" %}

{% block title%}설문 결과{%endblock title%}
{% block contents%}
    <h1>설문 투표 결과</h1>
    <h2>{{question.pk}}. {{question.question_text}}</h2>
    <ol>
        {% for choice in question.choice_set.all %}
            <li>{{choice.choice_text}} - {{choice.votes}}</li>
        {% endfor %}
    </ol>
{%endblock contents%}

polls/templates/polls/welcome.html
<!-- polls/templates/polls/welcome.html: (django) template 파일(동적처리)-->
{% extends "layouts/main_layout.html" %}

{% block title%}설문 홈{%endblock title%}
{% block contents%}
    <h1>설문조사 앱입니다.</h1>
    <h2>{{name}}님 안녕하세요.</h2>
    현재시간: <b>{{now}}</b>  
    {# {{now}} -> view에서 now라는 이름으로 전달된 값을 출력 #}
{% endblock contents%}